### ISSUE TITLE
. cannot be used in package name

### ISSUE THREAD

**Issue by joshikosuru** [helsing-ai/buffrs#155]
Only ASCII lowercase alphanumeric characters and dashes are accepted in the package name and no `.`. Is there any specific reason for doing so?

**Comment by xfbs** [comment]
Hey @joshikosuru, this is a good question. I don't know the full rationale for this, but I can explain to you the most likely rationale.

The main goal that we want to achieve is allow you to publish and reuse protocol buffer definitions. In order to do that, we want to make it as painless as possible, and prevent any potential surprises.

Specifically, we want to ensure that packages do not clash. This means that we want to prevent buffrs packages from defining colling `protobuf` packages and types. 

So, if we did allow you to publish packages with dots in them, you could end up in a situation where:

- There is a `physics` package that exports a `physics.temperature.Celsius` message.
- There is a `physics.temperature` package the exports a `physics.temperature.Celsius` message.

In this situation, if you depended on both of these packages (or any dependencies depended on them downstream), your build would be bricked.

So, to avoid this, we have a rule that every package needs to have a unique name consisting of only lowercase ASCII characters, numbers and dashes (or hyphens). That way, we can guarantee that you cannot accidentally import packages which break each other. 

I hope this explanation was helpful. Keep in mind that this is open source, if you think this decision is not done well, feel free to suggest alternative rules and we can check if they would be workable and what the tradeoffs would be.

Cheers :)

**Comment by mara-schulke** [comment]
Hi @joshikosuru, as @xfbs clarified, `.` is not possible in the package name, as it breaks the mapping between protobuf packages to buffrs packages.

Currently each buffrs packages has a kebab case name requirement which is then mapped to a snake case name protobuf package.

So `name = "google-types"` would become `package google_types;` – the rationale behind not introducing dots is to simplify the mapping and keep package names consistent in format.
