### ISSUE TITLE
Encode manifest version in manifest

### ISSUE THREAD

**Issue by asmello** [helsing-ai/buffrs#64]
Yes - it's typical to store a 'manifest version' in the manifest so compatibility can be flagged if breaking changes are made. This avoids semantic misinterpretation, making it easy to ahead-of-time surface "buffrs is out of date" rather than surfacing "some field is missing".

e.g. store

```
manifest-version: "1.2"
```

and if buffrs reads a manifest it can't interpret (because it uses some incompatible feature) you can error that the manifest is out of date.

_Originally posted by @j-baker in https://github.com/helsing-ai/buffrs/pull/38#discussion_r1331132029_

**Comment by mara-schulke** [comment]
I think this is a good idea – but way to early. For now i would like to break things frequently to keep technical debt as low as possible until we reach v1

**Comment by j-baker** [comment]
I think you have it backwards here. The version is what gives you the ability to make breaking changes, rather than the thing which stops you from doing so.

- Without the version, you ship some break. Your users' scripts now _may or may not_ work when resolving dependencies. Errors may be meaningless. You spend lots of time supporting users.
- With the version, you ship some break. You increment the manifest version. Users receive an error saying 'manifest version incompatible - you need to update buffrs'. Intended action much easier, much less support for you, much less pain for them. Users are comfortable with you stabilising a bit later, are comfortable with you making bigger breaks.

Does that make sense?

**Comment by mara-schulke** [comment]
@j-baker yes of course. My point was that I would like to prevent us having tens of manifest versions. We could do a `unstable.xyz` version which we then use to form a meaningful 1.0?

What do you think?
